project_id = "gepwifrsudifmcjfeugs"

[functions.rooms]
verify_jwt = true

[functions.allocate-room]
verify_jwt = true

[functions.my-allocation]
verify_jwt = true

[functions.student-login]
verify_jwt = false
