[functions.student-login]
verify_jwt = false

[functions.rooms]
verify_jwt = false

[functions.allocate-room]
verify_jwt = false

[functions.my-allocation]
verify_jwt = false

[functions.get-student-phone]
verify_jwt = false

[functions.update-student-phone]
verify_jwt = false