name: Deploy Supabase
on:
  push:
    branches: [main]
    paths: ['supabase/**']
  workflow_dispatch:
concurrency: supabase-production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with: {version: latest}
      - run: supabase link --project-ref "${{ secrets.gepwifrsudifmcjfeugs }}"
        env: {SUPABASE_ACCESS_TOKEN: '${{ secrets.sbp_79385e5cec19c20fe8be0e8e10a0c348f0859197 }}'}
      - run: supabase db push
        env: {SUPABASE_ACCESS_TOKEN: '${{ secrets.sbp_79385e5cec19c20fe8be0e8e10a0c348f0859197 }}'}
      - run: supabase functions deploy rooms
        env: {SUPABASE_ACCESS_TOKEN: '${{ secrets.sbp_79385e5cec19c20fe8be0e8e10a0c348f0859197 }}'}
      - run: supabase functions deploy allocate-room
        env: {SUPABASE_ACCESS_TOKEN: '${{ secrets.sbp_79385e5cec19c20fe8be0e8e10a0c348f0859197 }}'}
      - run: supabase functions deploy my-allocation
        env: {SUPABASE_ACCESS_TOKEN: '${{ secrets.sbp_79385e5cec19c20fe8be0e8e10a0c348f0859197 }}'}
      - run: supabase functions deploy student-login
        env: {SUPABASE_ACCESS_TOKEN: '${{ secrets.sbp_79385e5cec19c20fe8be0e8e10a0c348f0859197 }}'}
